//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CatagoryId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<double> BookingAmount { get; set; }
        public string BookingNaration { get; set; }
        public string SerialNo { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string Status { get; set; }
        public string BookingBY { get; set; }
        public Nullable<int> ExecutiveId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
