//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerAltMobile { get; set; }
        public string CustomerOccupation { get; set; }
        public string OfficeNo { get; set; }
        public Nullable<System.DateTime> CustomerDob { get; set; }
        public Nullable<System.DateTime> CustomerAnnDate { get; set; }
        public string Refrence { get; set; }
        public string CustomerNo { get; set; }
        public Nullable<int> ExecutiveId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string GurantorName { get; set; }
        public string GurantorNo { get; set; }
        public string GurantorContatNo { get; set; }
        public string Pin { get; set; }
        public Nullable<int> FranchiseId { get; set; }
        public string PhotoPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
