//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustBooking
    {
        public int BookingId { get; set; }
        public string CustomerName { get; set; }
        public string MobileNo { get; set; }
        public string AltMobileNo { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> ExecutiveId { get; set; }
    }
}
