//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DealerSale()
        {
            this.DealerSaleDetails = new HashSet<DealerSaleDetail>();
        }
    
        public int SaleId { get; set; }
        public string DealerName { get; set; }
        public string DealerContactNo { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<double> TotalPaid { get; set; }
        public Nullable<double> Remaining { get; set; }
        public string Naration { get; set; }
        public Nullable<System.DateTime> NextPaymentDate { get; set; }
        public string SaleNo { get; set; }
        public string AccNo { get; set; }
        public string SaleMode { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string SaleStatus { get; set; }
        public string SendSms { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerSaleDetail> DealerSaleDetails { get; set; }
    }
}
