//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerSaleDetail
    {
        public int SaledetailId { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string SerialNo { get; set; }
        public Nullable<double> ProductPrice { get; set; }
    
        public virtual DealerSale DealerSale { get; set; }
    }
}
