//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AjayDbEntities : DbContext
    {
        public AjayDbEntities()
            : base("name=AjayDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<ApprovedReceipt> ApprovedReceipts { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Catagory> Catagories { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CustBooking> CustBookings { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DealerSale> DealerSales { get; set; }
        public virtual DbSet<DealerSaleDetail> DealerSaleDetails { get; set; }
        public virtual DbSet<ElectronicModel> ElectronicModels { get; set; }
        public virtual DbSet<EMIDetail> EMIDetails { get; set; }
        public virtual DbSet<EMIDetailsDummy> EMIDetailsDummies { get; set; }
        public virtual DbSet<Executive> Executives { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<FranchiseInfo> FranchiseInfoes { get; set; }
        public virtual DbSet<FranchiseProfile> FranchiseProfiles { get; set; }
        public virtual DbSet<LateFee> LateFees { get; set; }
        public virtual DbSet<NewCustomer> NewCustomers { get; set; }
        public virtual DbSet<OwnStock> OwnStocks { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<PurchaseSerialNo> PurchaseSerialNoes { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<StockOrder> StockOrders { get; set; }
        public virtual DbSet<StockSerialNo> StockSerialNoes { get; set; }
        public virtual DbSet<TellyFeedback> TellyFeedbacks { get; set; }
        public virtual DbSet<UserInRole> UserInRoles { get; set; }
        public virtual DbSet<UserMembership> UserMemberships { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
