//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Executive
    {
        public int ExecutiveId { get; set; }
        public string ExecutiveName { get; set; }
        public string ExecutiveContactNo { get; set; }
        public string ExecutiveAddress { get; set; }
        public string ExecutiveALtNo { get; set; }
    }
}
