//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchiseInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FranchiseInfo()
        {
            this.OwnStocks = new HashSet<OwnStock>();
            this.StockOrders = new HashSet<StockOrder>();
        }
    
        public int FranchiseId { get; set; }
        public string FranchiseName { get; set; }
        public string FranchiseAddress { get; set; }
        public string FranchiseCity { get; set; }
        public string FranchiseState { get; set; }
        public string FranchiseTelephoneNo { get; set; }
        public string FranchiseBusinessTeleNo { get; set; }
        public string FranchiseContactPersonName { get; set; }
        public string FranchiseContactPersonPhoneNo { get; set; }
        public string FranchiseContactPersonAltPhoneNo { get; set; }
        public string FranchiseContactPersonEmail { get; set; }
        public string FranchiseContactPersonAddress { get; set; }
        public string FranchiseContactPersonCity { get; set; }
        public string FranchiseVatTinNo { get; set; }
        public Nullable<double> FranchiseVatRate { get; set; }
        public string FranchiseServiceTaxNo { get; set; }
        public Nullable<double> FranchiseServicetaxRate { get; set; }
        public System.DateTime FranchiseCreatedate { get; set; }
        public Nullable<System.DateTime> FranchiseLastmodifyDate { get; set; }
        public Nullable<bool> FranchiseStatus { get; set; }
        public Nullable<System.DateTime> FranchiseOwnerDob { get; set; }
        public Nullable<System.DateTime> MembershipRequestMarriageAniversary { get; set; }
        public string FranchisePinCode { get; set; }
        public string FranchiseCountry { get; set; }
        public string FranchiseCode { get; set; }
        public Nullable<System.DateTime> CodeGenerateDate { get; set; }
        public Nullable<int> Shop { get; set; }
    
        public virtual FranchiseProfile FranchiseProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OwnStock> OwnStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockOrder> StockOrders { get; set; }
    }
}
