//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchiseProfile
    {
        public int FranchiseID { get; set; }
        public Nullable<int> UserProfileID { get; set; }
        public string FranchiseUserName { get; set; }
        public string FranchisePassword { get; set; }
        public string FranchiseConfirmPassword { get; set; }
    
        public virtual FranchiseInfo FranchiseInfo { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
