//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LateFee
    {
        public int LateId { get; set; }
        public double LateFeeAmount { get; set; }
        public System.DateTime LateDate { get; set; }
        public int EMIId { get; set; }
    
        public virtual EMIDetail EMIDetail { get; set; }
    }
}
