//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseSerialNo
    {
        public int SerialId { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CatagoryId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> FrachiseId { get; set; }
        public string SaleTo { get; set; }
        public string SaleMode { get; set; }
    
        public virtual Catagory Catagory { get; set; }
        public virtual Company Company { get; set; }
        public virtual ElectronicModel ElectronicModel { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
