//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.EMIDetails = new HashSet<EMIDetail>();
            this.EMIDetailsDummies = new HashSet<EMIDetailsDummy>();
        }
    
        public int SaleId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public string SaleMode { get; set; }
        public Nullable<double> AdvanceDownPayment { get; set; }
        public Nullable<double> BalanceAmount { get; set; }
        public Nullable<int> NoOfEmi { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string SaleNaration { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string SaleNo { get; set; }
        public Nullable<double> EMI { get; set; }
        public string AccountNo { get; set; }
        public Nullable<double> DocumentCharges { get; set; }
        public Nullable<int> ElectronicCatagoryId { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> FranchiseId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string SaleStatus { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<System.DateTime> NextPaymentDate { get; set; }
        public Nullable<double> DealerBalanceAmt { get; set; }
        public string SaleOf { get; set; }
        public Nullable<double> Discount { get; set; }
        public string SendSms { get; set; }
        public Nullable<System.DateTime> SaleCompletedDate { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMIDetail> EMIDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMIDetailsDummy> EMIDetailsDummies { get; set; }
        public virtual Sale Sale1 { get; set; }
        public virtual Sale Sale2 { get; set; }
    }
}
