//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSerialNo
    {
        public int SerialId { get; set; }
        public Nullable<int> StockTransferId { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CatagoryId { get; set; }
        public Nullable<int> ModelId { get; set; }
    
        public virtual StockSerialNo StockSerialNo1 { get; set; }
        public virtual StockSerialNo StockSerialNo2 { get; set; }
    }
}
