//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOrder
    {
        public int StockOrderId { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<int> ComapnyId { get; set; }
        public Nullable<int> CatagoryId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Naration { get; set; }
        public Nullable<int> FranchiseId { get; set; }
    
        public virtual Catagory Catagory { get; set; }
        public virtual Company Company { get; set; }
        public virtual ElectronicModel ElectronicModel { get; set; }
        public virtual FranchiseInfo FranchiseInfo { get; set; }
    }
}
