//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TellyFeedback
    {
        public int FeedbackId { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public string Resopnce { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> NextCallDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual NewCustomer NewCustomer { get; set; }
    }
}
