//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajay.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInRole
    {
        public int UserInRoleId { get; set; }
        public int RoleId { get; set; }
        public int UserId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
